project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "David Redek"
  search: false
  navbar:
    left:
      - text: about
        href: index.qmd
      - text: projects
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/davidredek
      - icon: linkedin
        href: https://www.linkedin.com/in/david-redek/

format:
  html:
    theme: cosmo
    # Add this section to override colors
    theme-rules:
      - navbar-bg: "#2c3e50" # A dark slate gray
      - navbar-fg: "#ffffff" # White text
    css: styles.css
    toc: true

editor: visual

