project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "David Redek"
  search: false
  navbar:
    fixed: true
    left:
      - text: about
        href: index.qmd
      - text: research
        href: research.qmd
      - text: fun projects
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/davidredek
      - icon: linkedin
        href: https://www.linkedin.com/in/david-redek/

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    headroom: false

editor: visual

